/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "html",
      className: "sidebar-title",
      value: "About Web3Privacy Now",
      defaultStyle: true,
    },
    'welcome',
    'manifesto',
    'roadmap',
    'history',
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "html",
      className: "sidebar-title",
      value: "Projects",
      defaultStyle: true,
    },
    {
      type: "category",
      label: "Research",
      items: [{type: 'autogenerated', dirName: 'research'}],
    },
    {
      type: "category",
      label: "Events",
      link: {type: 'doc', id: 'events/index'},
      items: [{type: 'autogenerated', dirName: 'events'}],
    },
    'projects/privacy-explorer',
    'projects/privacy-tech-awards',
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "html",
      className: "sidebar-title",
      value: "Community",
      defaultStyle: true,
    },
    'follow-us',
    'get-involved',
    'donate',
    'communication',
    'contacts',
    'code-of-conduct',
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "html",
      className: "sidebar-title",
      value: "Governance",
      defaultStyle: true,
    },
    'core-team',
    'workgroups',
    'governance/pm',
    'git',
    'governance/multisig',
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "html",
      className: "sidebar-title",
      value: "Others",
      defaultStyle: true,
    },
    'funding-requests',
  ],

};

export default sidebars;
